-- HomePage: single row for social embed links (Instagram, LinkedIn).
-- Columns are quoted so they match the app (InstagramPost, LinkedInPost).

CREATE TABLE IF NOT EXISTS "HomePage" (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "InstagramPost" TEXT,
  "LinkedInPost" TEXT
);

-- Ensure there is at least one row (only if table is empty)
INSERT INTO "HomePage" ("InstagramPost", "LinkedInPost")
SELECT NULL, NULL
WHERE NOT EXISTS (SELECT 1 FROM "HomePage" LIMIT 1);

-- If your table already exists with different column names (e.g. lowercase), run in Supabase SQL Editor:
-- ALTER TABLE "HomePage" RENAME COLUMN instagrampost TO "InstagramPost";  -- if you have instagrampost
-- ALTER TABLE "HomePage" RENAME COLUMN linkedinpost TO "LinkedInPost";    -- if you have linkedinpost
-- And ensure you have an id column: ALTER TABLE "HomePage" ADD COLUMN IF NOT EXISTS id BIGSERIAL PRIMARY KEY;
