-- History: team/car history entries
CREATE TABLE IF NOT EXISTS "History" (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  year INTEGER NOT NULL,
  name TEXT NOT NULL,
  nickname TEXT,
  image TEXT NOT NULL,
  highlight TEXT,
  specs JSONB NOT NULL DEFAULT '[]',
  "order" INTEGER NOT NULL DEFAULT 0
);

-- Sponsors: sponsor tiers and logos
CREATE TABLE IF NOT EXISTS "Sponsors" (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  logo TEXT NOT NULL,
  url TEXT,
  tier TEXT NOT NULL,
  "order" INTEGER NOT NULL DEFAULT 0
);

-- Departments: team departments
CREATE TABLE IF NOT EXISTS "Departments" (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  description TEXT NOT NULL,
  image TEXT NOT NULL,
  link TEXT,
  "order" INTEGER NOT NULL DEFAULT 0
);

-- CarSubsystems: car subsystems/specs
CREATE TABLE IF NOT EXISTS "CarSubsystems" (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  description TEXT NOT NULL,
  specs JSONB NOT NULL DEFAULT '[]',
  "order" INTEGER NOT NULL DEFAULT 0
);

-- Optional: enable RLS and add policies if you want row-level security
-- ALTER TABLE "History" ENABLE ROW LEVEL SECURITY;
-- ALTER TABLE "Sponsors" ENABLE ROW LEVEL SECURITY;
-- ALTER TABLE "Departments" ENABLE ROW LEVEL SECURITY;
-- ALTER TABLE "CarSubsystems" ENABLE ROW LEVEL SECURITY;
